#!/bin/bash

echo "Enter your number: "
read num
echo " "

for (( i=1; i<=$num;i++ ));  do
	if ((i%15==0)); then
		echo "FizzBuzz"
	elif ((i%3==0)); then
		echo "Fizz"
	elif ((i%5==0)); then
		echo "Buzz"
	else
		echo $i
		
	fi;
done	

echo "Done"				
